# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 340)
        MainWindow.setMinimumSize(QtCore.QSize(500, 340))
        MainWindow.setMaximumSize(QtCore.QSize(550, 350))
        MainWindow.setStyleSheet("background-color: rgb(180, 180, 181);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(229, 233, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(481, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Images/laptop battery.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 6, 1)
        spacerItem = QtWidgets.QSpacerItem(61, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.testNumLabel = QtWidgets.QLabel(self.centralwidget)
        self.testNumLabel.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.testNumLabel.setFont(font)
        self.testNumLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.testNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testNumLabel.setObjectName("testNumLabel")
        self.horizontalLayout.addWidget(self.testNumLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(61, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(231, 0))
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 3)
        self.startInLabel = QtWidgets.QLabel(self.centralwidget)
        self.startInLabel.setMinimumSize(QtCore.QSize(231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.startInLabel.setFont(font)
        self.startInLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.startInLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startInLabel.setObjectName("startInLabel")
        self.gridLayout.addWidget(self.startInLabel, 3, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(231, 0))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 3)
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setMinimumSize(QtCore.QSize(231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 5, 1, 1, 3)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(231, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 44, 93);\n"
"text-transform: uppercase;\n"
"font-weight: bold;\n"
"font-size: 25px;")
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 6, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Battery Check"))
        self.label_3.setText(_translate("MainWindow", "Test №:"))
        self.testNumLabel.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "start in"))
        self.startInLabel.setText(_translate("MainWindow", "00-00-0000 00-00"))
        self.label_5.setText(_translate("MainWindow", "total time"))
        self.timeLabel.setText(_translate("MainWindow", "00-00"))
        self.startButton.setText(_translate("MainWindow", "start"))
